language: ruby
rvm:
  - 2.4.4
env:
  - ALGOLIASEARCH_APPLICATION_ID=''
  - ALGOLIASEARCH_API_KEY=''
  - ALGOLIASEARCH_API_KEY_SEARCH=''
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres