language: ruby
rvm:
- 2.4.4
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  api_key:
    secure: OZpTfrP7+0a1MQNRf7do+gVAEL/0LJzNax2bZcdtSNgdB+25fk6d07sJSyHlDseER29r60PlzZytw38COVG+wTqWV1e+reiQcmbzwJiAF+lVjsUIcd0wsxKhllZ0TECCPW3ldyHy5yN+o0aQevtA3wQsQfBf0LC6PRatOJB1GpXlPqHg4s3uBDDAy0i6uIHAoFBlhJSLb14H0BQ2FbfTCqo4du5QIli3pkEWZwHqvX++iNWdJBvOxXGh3zoN/QE4M7TqSQP4m98zUy/nEd6Wj98No13bh0cJ7lSUrsIKDESl0DqW4rmMwEdLrSy4SK40FyG5sGwrHyO9CrKuSgKHYJOvPPJmT/HkdlTQcwKse/P5jUaxfaCaTJ9t3ZzHUGBJz8VSsVRySFBWqYDQsCT560wyxI9pBu3ccCqVTCVTJO5ceThlk+VJ4iAi7ZICBDwgSd9TJOaNrjDfg16MFBSe1tPWMhk81QYTb7sW+vZpIz0nbuxptFg46k2nRFcZu4JSF+wTIhihElYvbxyz6nnk/BS45gZCkx5zWzdXFQjR+os4ohqga1VXJ0s4nOt2txnwqMhgHuDVS0aX/074eBDvUAqyJZnqyV91eBaNeb1DFK8dadnma8bK1INq1lQrBGtycahPIdaXb4wE/RpKZA5C9LFfsZB10AYjUK/dU73vIoU=
