language: ruby
rvm:
- 2.4.4
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: JWSuNXjViOMtmAOlV4OME6kGTCu6QGsyO6q5jgGgfRHLysW8Et8pDpyp/f2yXq71MyO9h9kQz2ZMNP4JJe6yaQ8Z+qgNcWkq/vRv85xXJz0bqS+/VGsuVOmeaaXyRkfwRyRwSvLAQe+Y52acDLIX5Hsk6fTRoFJguooe9OdCCeAF4jbZMHLuccKv8B41tUPKNP3wk8eIdRLOOcGjfsgTUlzs1pXgcLho1BzHnYOY59GRAWUGTd1CW5gDwW408op8U+G/dUUlFTH7mSd5eScoOAl9oabTOAnxCfSFjqA9F8AJcYFmuC76ibumt4frSOC0ydezz1LLcTCdnaezjZ6q0IOhex7xUOUwKOqvUnl6QyDsxiEw86aaH+BXcCQdh5tSIZRI3/jJ7eqPDgQF0uXkiXoJDWYWRKphdHZMKJBh57nBsdP413wFtk4Apdbc91xcWp5ZxUc/Ffc+pPPEkHwM/MMKVhkFdI4wVmFAYxRrHl3T9vecojW0CRo23Dc3WaK2pgnpiOLyTopGd8Cde6GZcn278r6JaH3FkZ1wuQ7taam0xfVSCW+4vA5e8fRg2UnO/lbIzkqMPioXoWnCWmJ2WxApXbxxmnMlxXrglH0gy2QZgv4/ZcVl4pKIUCFybvnUt8rPMqJ6Gu+cQxwgvUV5yz2wqfo2bIW5dc8Yivchkw0=
  app: inaturalist
  on:
    repo: vincentopensourcetaiwan/inaturalist
