language: ruby
rvm:
- 2.4.4
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Dn1TuKKQcwviVa65KHESMkMcfyW8evmx8qv6oZUsR08Hq7TZglfwFnESjq/Y13Q4hPpAVsyxl0CYBpjHCaOBPyFDZln8yqW1YJIRFfUqzV3XJh44roAIC4qLlqZiGIzA8tVGzTgGFTNwLGZOY/QYL5zt9vnHMhyIBWMAQNXXxnCO2OkaTrf1fnupry80iZjJu9MfpMZprczAMk2KuIVLXXiLWGcptNY/3m3Je4syzSFLK+ThYBF+fKuuQUTfdnicR1ABopahpMHSg2Kk32DoLoTY01QZMu+31NxV8tLaXtKhIYXmjJTgn8kSJ6bmtNzIFqNcizV+iyVoCNOnaBDlRM2pz/fXY7aywDqIb+YA4iK4bbWAiPbBz8eGkGt174eo815dtUpjiKViFIDzBwrm37VNfWyQw0lKGv0OeThV3m0NVEObz4IdFHepmT6rtuTqWDSaWK9LBSZ/n8wDRB0KqcOx6H/8cJIpJMMd3OjDSjaPFLwZFFcnzkqA0j55A94sNtZ/wMvU6DQD7c9j7BFgEvFi2JbLwSBH1aWpN8OjMCMuEjngaaBh/Pl1RGS9VuwvJBA0XhLAR2FGw2zs0lMvwAalp4mebGpI0OZh3BWsWDb8zExG98dD9Lqc1jNwyyYiMDRjqJUEcNl1zcE3XwhRlFdMyxrKhMyIbsuXjW4Ij4M=
  app: inaturalist
  on:
    repo: vincentopensourcetaiwan/inaturalist
