language: ruby
rvm:
- 2.4.4
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Pib+qUWbTnMYEcHCeCrQ5T/YGv4ZlCzgqwICn4s7Egbl5dETMY5yjnzOHWPqCQfrBcMNQJJWY2Zd6LEHqu/f9PnePiL5G6zblxGND7Jl11dcp+M0gMzSKmRYA3LtbC8u0ifOayY4HMP1WmwNcflYM9Os3pyRKZiUVilnTPKRoVeWbwCu8ILK6yA87NcOg8LCKUDDFAJQ+iIPtqGmvj+9bTKRZXRXhVDnVBT9kAGTqCByua8QUcEz7WBQkmfLkyrYrzFsuxh7TX266XcKtimBu4J18+ZQXpFMDgpkMTz5pFqlVdv1rSiyN/NmIGtqfZMhwyUaK1bV3C2BfpDALE/XHYrsVybcQiqrvDv2iONnICIhXHOebfkeFhRdktzVUsk5FkEdZqT8LzUwYZ6hhTpT48EhRC08LaDg4na9fPMgsFUlVtCBsMbD7MIMWxoNmjx+tPToUVkWqkmhrEH9PxNu4BhOAf67G6mk0EexkcKSs9ozsM1BkTuEC0w8tf4PSN7QvUY5eDX37W++eTKO3tMlXcGJ+cNf+Dj8idzdtiaIR9yXPgsLKHccexvGDJOCyKvAAINlP1L0AwVMrP3+IWGZoLg6mDL7QPUiFyNnHsnmxZO+wHkQZZrD0PpjqEUWMcrbLfGytUM5GLAGoL+xNJlpQnxldX8KMzeKhH7PAC0yUUY=
  app: inaturalist
  on:
    repo: vincentopensourcetaiwan/inaturalist
